name: pruebas-unitarias

on:
  push:
    branches:
      - "*" 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Instalar todas las dependencias
        run: npm install

      - name: Ejecutar test
        run: npm test